// Generated by socket_layout.py
// Bin: 3×4 gridfinity units  (126×168mm)
// Content: 120.0×158.7mm  (margins: x=3.0mm, y=4.7mm)

include <src/core/standard.scad>
use <src/core/gridfinity-rebuilt-utility.scad>
use <src/core/gridfinity-rebuilt-holes.scad>
use <src/core/bin.scad>
use <src/core/cutouts.scad>
use <src/helpers/generic-helpers.scad>
use <src/helpers/grid.scad>
use <src/helpers/grid_element.scad>

$fa = $preview ? 10 : 4;
$fs = $preview ? 1.5 : 0.25;

gridx = 3;
gridy = 4;
gridz = 3;  // 21mm total height; fits 12mm socket depth

gridz_define = 0;
height_internal = 0;
enable_zsnap = false;
include_lip = true;
half_grid = false;

only_corners = false;
refined_holes = true;
magnet_holes = false;
screw_holes = false;
crush_ribs = true;
chamfer_holes = true;
printable_hole_top = true;
enable_thumbscrew = false;

hole_options = bundle_hole_options(refined_holes, magnet_holes, screw_holes,
                                   crush_ribs, chamfer_holes, printable_hole_top);

bin1 = new_bin(
    grid_size       = [gridx, gridy],
    height_mm       = height(gridz, gridz_define, enable_zsnap),
    fill_height     = height_internal,
    include_lip     = include_lip,
    hole_options    = hole_options,
    only_corners    = only_corners || half_grid,
    thumbscrew      = enable_thumbscrew,
    grid_dimensions = GRID_DIMENSIONS_MM / (half_grid ? 2 : 1)
);

socket_depth = 12;
c_chamfer    = 0.5;
label_height = 0.6;
label_size   = 4.83;
label_font   = "Liberation Sans:style=Bold";
label_z = BASE_HEIGHT + bin_get_infill_size_mm(bin1).z + TOLLERANCE;

bin_render(bin1) {

    // === Imp Deep ===
    translate([ -28.800,   73.125]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 5/32
    translate([ -14.400,   73.125]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 3/16
    translate([  -0.000,   73.125]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 7/32
    translate([  14.400,   73.125]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 1/4
    translate([  28.800,   73.125]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 9/32
    translate([ -44.425,   51.300]) cut_chamfered_cylinder(6.9, socket_depth, c_chamfer);  // 5/16
    translate([ -28.625,   51.300]) cut_chamfered_cylinder(6.9, socket_depth, c_chamfer);  // 11/32
    translate([ -12.275,   51.300]) cut_chamfered_cylinder(7.45, socket_depth, c_chamfer);  // 3/8
    translate([   5.475,   51.300]) cut_chamfered_cylinder(8.3, socket_depth, c_chamfer);  // 7/16
    translate([  24.900,   51.300]) cut_chamfered_cylinder(9.125, socket_depth, c_chamfer);  // 1/2

    // === Imp Shallow ===
    translate([  45.175,   51.300]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 5/32
    translate([ -44.800,   28.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 3/16
    translate([ -30.500,   28.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 7/32
    translate([ -16.200,   28.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 1/4
    translate([  -1.900,   28.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 9/32
    translate([  12.400,   28.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 5/16
    translate([  27.300,   28.225]) cut_chamfered_cylinder(6.75, socket_depth, c_chamfer);  // 11/32
    translate([  43.500,   28.225]) cut_chamfered_cylinder(7.45, socket_depth, c_chamfer);  // 3/8
    translate([ -47.900,    5.225]) cut_chamfered_cylinder(9.05, socket_depth, c_chamfer);  // 7/16
    translate([ -27.800,    5.225]) cut_chamfered_cylinder(9.05, socket_depth, c_chamfer);  // 1/2

    // === Met Shallow ===
    translate([  -7.600,    5.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 4
    translate([   6.700,    5.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 5
    translate([  21.000,    5.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 6
    translate([  35.300,    5.225]) cut_chamfered_cylinder(6.15, socket_depth, c_chamfer);  // 7
    translate([  50.200,    5.225]) cut_chamfered_cylinder(6.75, socket_depth, c_chamfer);  // 8
    translate([ -47.950,  -19.425]) cut_chamfered_cylinder(6.75, socket_depth, c_chamfer);  // 9
    translate([ -31.800,  -19.425]) cut_chamfered_cylinder(7.4, socket_depth, c_chamfer);  // 10
    translate([ -14.150,  -19.425]) cut_chamfered_cylinder(8.25, socket_depth, c_chamfer);  // 11
    translate([   5.200,  -19.425]) cut_chamfered_cylinder(9.1, socket_depth, c_chamfer);  // 12
    translate([  25.400,  -19.425]) cut_chamfered_cylinder(9.1, socket_depth, c_chamfer);  // 13
    translate([  45.600,  -19.425]) cut_chamfered_cylinder(9.1, socket_depth, c_chamfer);  // 14

    // === Met Deep ===
    translate([ -29.050,  -41.425]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 4
    translate([ -14.650,  -41.425]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 5
    translate([  -0.250,  -41.425]) cut_chamfered_cylinder(6.2, socket_depth, c_chamfer);  // 6
    translate([  14.200,  -41.425]) cut_chamfered_cylinder(6.25, socket_depth, c_chamfer);  // 7
    translate([  28.850,  -41.425]) cut_chamfered_cylinder(6.4, socket_depth, c_chamfer);  // 8
    translate([ -49.450,  -64.075]) cut_chamfered_cylinder(6.85, socket_depth, c_chamfer);  // 9
    translate([ -33.150,  -64.075]) cut_chamfered_cylinder(7.45, socket_depth, c_chamfer);  // 10
    translate([ -15.350,  -64.075]) cut_chamfered_cylinder(8.35, socket_depth, c_chamfer);  // 11
    translate([   4.150,  -64.075]) cut_chamfered_cylinder(9.15, socket_depth, c_chamfer);  // 12
    translate([  25.050,  -64.075]) cut_chamfered_cylinder(9.75, socket_depth, c_chamfer);  // 13
    translate([  46.550,  -64.075]) cut_chamfered_cylinder(9.75, socket_depth, c_chamfer);  // 14
}

translate([0, 0, label_z]) {

    // === Imp Deep ===
    translate([ -28.800,   64.111]) linear_extrude(label_height) text("5/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -14.400,   64.111]) linear_extrude(label_height) text("3/16", size=label_size, font=label_font, halign="center", valign="center");
    translate([  -0.000,   64.111]) linear_extrude(label_height) text("7/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([  14.400,   64.111]) linear_extrude(label_height) text("1/4", size=label_size, font=label_font, halign="center", valign="center");
    translate([  28.800,   64.111]) linear_extrude(label_height) text("9/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -38.425,   41.586]) linear_extrude(label_height) text("5/16", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -23.625,   39.172]) linear_extrude(label_height) text("11/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -10.275,   41.036]) linear_extrude(label_height) text("3/8", size=label_size, font=label_font, halign="center", valign="center");
    translate([   5.475,   40.186]) linear_extrude(label_height) text("7/16", size=label_size, font=label_font, halign="center", valign="center");
    translate([  29.900,   39.361]) linear_extrude(label_height) text("1/2", size=label_size, font=label_font, halign="center", valign="center");

    // === Imp Shallow ===
    translate([  51.175,   42.336]) linear_extrude(label_height) text("5/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -38.800,   19.261]) linear_extrude(label_height) text("3/16", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -24.500,   19.261]) linear_extrude(label_height) text("7/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -11.200,   19.261]) linear_extrude(label_height) text("1/4", size=label_size, font=label_font, halign="center", valign="center");
    translate([   4.100,   19.261]) linear_extrude(label_height) text("9/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([  18.400,   19.261]) linear_extrude(label_height) text("5/16", size=label_size, font=label_font, halign="center", valign="center");
    translate([  32.300,   16.247]) linear_extrude(label_height) text("11/32", size=label_size, font=label_font, halign="center", valign="center");
    translate([  48.500,   17.961]) linear_extrude(label_height) text("3/8", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -47.900,   -6.639]) linear_extrude(label_height) text("7/16", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -27.800,   -6.639]) linear_extrude(label_height) text("1/2", size=label_size, font=label_font, halign="center", valign="center");

    // === Met Shallow ===
    translate([  -7.600,   -3.739]) linear_extrude(label_height) text("4", size=label_size, font=label_font, halign="center", valign="center");
    translate([   6.700,   -3.739]) linear_extrude(label_height) text("5", size=label_size, font=label_font, halign="center", valign="center");
    translate([  21.000,   -3.739]) linear_extrude(label_height) text("6", size=label_size, font=label_font, halign="center", valign="center");
    translate([  35.300,   -3.739]) linear_extrude(label_height) text("7", size=label_size, font=label_font, halign="center", valign="center");
    translate([  50.200,   -4.339]) linear_extrude(label_height) text("8", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -45.950,  -28.989]) linear_extrude(label_height) text("9", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -28.800,  -29.639]) linear_extrude(label_height) text("10", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -11.150,  -30.489]) linear_extrude(label_height) text("11", size=label_size, font=label_font, halign="center", valign="center");
    translate([   5.200,  -31.339]) linear_extrude(label_height) text("12", size=label_size, font=label_font, halign="center", valign="center");
    translate([  25.400,  -31.339]) linear_extrude(label_height) text("13", size=label_size, font=label_font, halign="center", valign="center");
    translate([  45.600,  -31.339]) linear_extrude(label_height) text("14", size=label_size, font=label_font, halign="center", valign="center");

    // === Met Deep ===
    translate([ -29.050,  -50.439]) linear_extrude(label_height) text("4", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -14.650,  -50.439]) linear_extrude(label_height) text("5", size=label_size, font=label_font, halign="center", valign="center");
    translate([  -0.250,  -50.439]) linear_extrude(label_height) text("6", size=label_size, font=label_font, halign="center", valign="center");
    translate([  16.200,  -50.489]) linear_extrude(label_height) text("7", size=label_size, font=label_font, halign="center", valign="center");
    translate([  30.850,  -50.639]) linear_extrude(label_height) text("8", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -49.450,  -73.739]) linear_extrude(label_height) text("9", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -33.150,  -74.339]) linear_extrude(label_height) text("10", size=label_size, font=label_font, halign="center", valign="center");
    translate([ -15.350,  -75.239]) linear_extrude(label_height) text("11", size=label_size, font=label_font, halign="center", valign="center");
    translate([   4.150,  -76.039]) linear_extrude(label_height) text("12", size=label_size, font=label_font, halign="center", valign="center");
    translate([  25.050,  -76.639]) linear_extrude(label_height) text("13", size=label_size, font=label_font, halign="center", valign="center");
    translate([  46.550,  -76.639]) linear_extrude(label_height) text("14", size=label_size, font=label_font, halign="center", valign="center");
}
